[package]
name = "sar-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
serde_json.workspace = true
walkdir.workspace = true
rpassword.workspace = true
getrandom.workspace = true
crc32fast.workspace = true
sar-core = { path = "../sar-core" }
sar-archive = { path = "../sar-archive" }
sar-compression = { path = "../sar-compression" }
sar-crypto = { path = "../sar-crypto" }
sar-cdc = { path = "../sar-cdc" }
sar-delta = { path = "../sar-delta" }
sar-fragmentation = { path = "../sar-fragmentation" }
sar-sparse = { path = "../sar-sparse" }
rustix = { version = "1.1.4", features = ["fs", "process"] }
filetime = "0.2.29"

[lints]
workspace = true

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.13"
serde_json.workspace = true
