[package]
name = "sar-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bitflags.workspace = true
serde.workspace = true
thiserror.workspace = true
sar-compression = { path = "../sar-compression" }

[dev-dependencies]
serde_json.workspace = true
tempfile = "3.13"

[lints]
workspace = true
