#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 M. Kasim Doenmez
# SPDX-License-Identifier: Apache-2.0

"""
Generate docs/API.md from docs/machine-readable/MACHINE_READABLE_API.json.

This generator expects schema_version 2.

It intentionally renders only a human-readable subset of the authoritative
machine-readable inventory:

  - crate name, path, status, and description
  - public-facing functions
  - public-facing types
  - public-facing constants, unless disabled

It does not render migration metadata, FFI readiness, milestone history,
security posture notes, crate-boundary rules, legacy data, module summaries,
or arbitrary unknown fields. Those belong in the JSON inventory or other
authoritative project documents, not in the human API overview.

Usage from repository root:

    python tools/generate_api_md.py

Check mode:

    python tools/generate_api_md.py --check

Optional:

    python tools/generate_api_md.py --no-constants
    python tools/generate_api_md.py --include-internal-public
    python tools/generate_api_md.py --include-unimplemented
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from mdgen import (
    heading,
    load_json,
    md_code,
    md_escape_cell,
    md_escape_text,
    normalize_markdown,
    to_ascii,
    write_or_check,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / "docs/machine-readable" / "MACHINE_READABLE_API.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "API.md"


HEADER = """<!--
SPDX-FileCopyrightText: 2026 M. Kasim Doenmez
SPDX-License-Identifier: Apache-2.0
-->

<!--
This file is generated from docs/machine-readable/MACHINE_READABLE_API.json.
Do not edit this file by hand.

Regenerate with:

    python tools/generate_api_md.py

Check without modifying files:

    python tools/generate_api_md.py --check
-->
"""


INTRO = """# API Inventory

This file is generated from `docs/machine-readable/MACHINE_READABLE_API.json`.

Do not edit this file by hand. Update `docs/machine-readable/MACHINE_READABLE_API.json` and regenerate this Markdown file instead.

`docs/machine-readable/MACHINE_READABLE_API.json` is the authoritative machine-readable API inventory. This file is a human-readable subset intended for browsing and review.

This document describes public-facing Rust APIs provided by the SAR reference implementation. It is not a protocol specification, security audit, stability guarantee, production-readiness claim, or replacement for crate-boundary documentation.

For protocol behavior, see `specification.md`.

For crate ownership and architecture boundaries, see `docs/CRATE_RESPONSIBILITIES.md`.

For conformance status, see `docs/CONFORMANCE.md`.
"""



def ensure_schema_v2(data: dict[str, Any]) -> None:
    version = data.get("schema_version")
    if version != 2:
        raise SystemExit(f"error: expected schema_version 2, got {version!r}")


def item_metadata(item: dict[str, Any]) -> dict[str, Any]:
    metadata = item.get("metadata")
    return metadata if isinstance(metadata, dict) else {}


def is_public_facing(
    item: dict[str, Any],
    *,
    include_internal_public: bool,
    include_unimplemented: bool,
) -> bool:
    metadata = item_metadata(item)

    implemented = metadata.get("implemented")
    if implemented is False and not include_unimplemented:
        return False

    visibility = metadata.get("visibility")
    if visibility not in (None, "public", "public_reexport"):
        return False

    stability = metadata.get("stability")
    if stability == "internal_public" and not include_internal_public:
        return False

    return True


def display_text(item: dict[str, Any]) -> str:
    return str(item.get("use_for") or item.get("description") or "")


def sort_key(item: dict[str, Any]) -> tuple[str, str]:
    return (
        str(item.get("name", "")).lower(),
        str(item.get("signature", "")).lower(),
    )


def render_summary(data: dict[str, Any]) -> str:
    crates = [crate for crate in data.get("crates", []) if isinstance(crate, dict)]

    lines: list[str] = []
    lines.append(heading(2, "Workspace Summary"))
    lines.append("| Crate | Status | Description |\n")
    lines.append("| --- | --- | --- |\n")

    for crate in crates:
        name = crate.get("name", "")
        status = crate.get("status", "")
        description = crate.get("description", "")
        lines.append(
            f"| {md_code(name)} | {md_code(status)} | {md_escape_cell(description)} |\n"
        )

    lines.append("\n")
    return "".join(lines)


def render_item_table(
    title: str,
    items: list[dict[str, Any]],
    *,
    include_kind: bool,
) -> str:
    if not items:
        return ""

    lines: list[str] = [heading(4, title)]

    if include_kind:
        lines.append("| Name | Kind | Signature | Description |\n")
        lines.append("| --- | --- | --- | --- |\n")
        for item in sorted(items, key=sort_key):
            signature = item.get("signature")
            lines.append(
                f"| {md_code(item.get('name', ''))} | "
                f"{md_code(item.get('kind', ''))} | "
                f"{md_code(signature) if signature else ''} | "
                f"{md_escape_cell(display_text(item))} |\n"
            )
    else:
        lines.append("| Name | Signature | Description |\n")
        lines.append("| --- | --- | --- |\n")
        for item in sorted(items, key=sort_key):
            lines.append(
                f"| {md_code(item.get('name', ''))} | "
                f"{md_code(item.get('signature', ''))} | "
                f"{md_escape_cell(display_text(item))} |\n"
            )

    lines.append("\n")
    return "".join(lines)


def render_examples(items: list[dict[str, Any]]) -> str:
    """Render examples only when explicitly present."""
    blocks: list[str] = []

    for item in sorted(items, key=sort_key):
        examples = item.get("examples")
        if not isinstance(examples, list) or not examples:
            continue

        blocks.append(heading(5, f"Examples for `{to_ascii(item.get('name', ''))}`"))

        for example in examples:
            if not isinstance(example, dict):
                continue

            title = example.get("title")
            language = to_ascii(example.get("language") or "rust")
            code = to_ascii(example.get("code") or "")

            if title:
                blocks.append(f"**{md_escape_text(title)}**\n\n")

            if code:
                blocks.append(f"```{language}\n{code.rstrip()}\n```\n\n")

    return "".join(blocks)


def render_crate(
    crate: dict[str, Any],
    *,
    include_constants: bool,
    include_internal_public: bool,
    include_unimplemented: bool,
) -> str:
    name = crate.get("name", "unnamed")
    path = crate.get("path", "")
    status = crate.get("status", "")
    description = crate.get("description", "")

    api = crate.get("api") if isinstance(crate.get("api"), dict) else {}

    functions = [
        item
        for item in api.get("functions", [])
        if isinstance(item, dict)
        and is_public_facing(
            item,
            include_internal_public=include_internal_public,
            include_unimplemented=include_unimplemented,
        )
    ]

    types = [
        item
        for item in api.get("types", [])
        if isinstance(item, dict)
        and is_public_facing(
            item,
            include_internal_public=include_internal_public,
            include_unimplemented=include_unimplemented,
        )
    ]

    constants = [
        item
        for item in api.get("constants", [])
        if isinstance(item, dict)
        and is_public_facing(
            item,
            include_internal_public=include_internal_public,
            include_unimplemented=include_unimplemented,
        )
    ]

    lines: list[str] = []
    lines.append(heading(3, f"`{to_ascii(name)}`"))
    lines.append(f"Path: {md_code(path)}\n\n")
    lines.append(f"Status: {md_code(status)}\n\n")
    lines.append(f"{md_escape_text(description)}\n\n")

    if not functions and not types and not (include_constants and constants):
        lines.append("No public-facing API items are listed for this crate.\n\n")
        return "".join(lines)

    lines.append(
        render_item_table(
            "Public functions",
            functions,
            include_kind=False,
        )
    )

    lines.append(
        render_item_table(
            "Public types",
            types,
            include_kind=True,
        )
    )

    if include_constants:
        lines.append(
            render_item_table(
                "Public constants",
                constants,
                include_kind=False,
            )
        )

    lines.append(render_examples(functions + types + constants))

    return "".join(lines)


def render_api_markdown(
    data: dict[str, Any],
    *,
    include_constants: bool,
    include_internal_public: bool,
    include_unimplemented: bool,
) -> str:
    ensure_schema_v2(data)

    crates = [crate for crate in data.get("crates", []) if isinstance(crate, dict)]

    parts: list[str] = [
        HEADER,
        INTRO,
        "\n",
        render_summary(data),
        heading(2, "Crates"),
    ]

    for crate in crates:
        parts.append(
            render_crate(
                crate,
                include_constants=include_constants,
                include_internal_public=include_internal_public,
                include_unimplemented=include_unimplemented,
            )
        )

    return normalize_markdown("".join(parts))


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"input JSON file, default: {DEFAULT_INPUT.relative_to(REPO_ROOT)}",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output Markdown file, default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)}",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if output file is missing or stale",
    )
    parser.add_argument(
        "--no-constants",
        action="store_true",
        help="omit public constants from the generated Markdown",
    )
    parser.add_argument(
        "--include-internal-public",
        action="store_true",
        help="include items marked stability=internal_public",
    )
    parser.add_argument(
        "--include-unimplemented",
        action="store_true",
        help="include items whose metadata says implemented=false",
    )

    args = parser.parse_args(argv)

    data = load_json(args.input)
    generated = render_api_markdown(
        data,
        include_constants=not args.no_constants,
        include_internal_public=args.include_internal_public,
        include_unimplemented=args.include_unimplemented,
    )

    return write_or_check(
        output_path=args.output,
        generated=generated,
        check=args.check,
        regenerate_command="python tools/generate_api_md.py",
    )


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
