#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 M. Kasim Doenmez
# SPDX-License-Identifier: Apache-2.0

"""
Generate docs/API.md from docs/MACHINE_READABLE_API.json.

Usage from repository root:

    python tools/generate_api_md.py

CI/check mode:

    python tools/generate_api_md.py --check

The generated Markdown is deterministic and intentionally contains no timestamp.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT = REPO_ROOT / "docs" / "MACHINE_READABLE_API.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "API.md"


SPDX_AND_GENERATED_HEADER = """<!--
SPDX-FileCopyrightText: 2026 M. Kasim Doenmez
SPDX-License-Identifier: Apache-2.0
-->

<!--
This file is generated from docs/MACHINE_READABLE_API.json.
Do not edit this file by hand.

Regenerate with:

    python tools/generate_api_md.py

Check without modifying files:

    python tools/generate_api_md.py --check
-->
"""


VISIBLE_INTRO = """# API Inventory

This document is generated from `docs/MACHINE_READABLE_API.json`.

Do not edit this file by hand. Update `docs/MACHINE_READABLE_API.json` and regenerate this document instead.

The machine-readable JSON file is the authoritative API inventory. This Markdown file is a human-readable projection for review and browsing.

This document describes the current public API inventory of the Rust reference implementation. It is not a protocol specification, security audit, stability guarantee, or production-readiness claim.

For authoritative protocol behavior, see `specification.md`.

For crate ownership and architectural boundaries, see `docs/CRATE_RESPONSIBILITIES.md`.

For conformance status, see `docs/CONFORMANCE.md`.
"""


def md_escape_cell(value: Any) -> str:
    """Escape a value for use inside a Markdown table cell."""
    text = scalar_to_text(value)
    text = text.replace("\\", "\\\\")
    text = text.replace("|", "\\|")
    text = text.replace("[", "\\[")
    text = text.replace("]", "\\]")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    text = text.replace("\n", "<br>")
    return text

def md_escape_text(value: Any) -> str:
    """Escape plain inline Markdown text without making it unreadable."""
    text = scalar_to_text(value)
    text = text.replace("\\", "\\\\")
    text = text.replace("[", "\\[")
    text = text.replace("]", "\\]")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    return text

def scalar_to_text(value: Any) -> str:
    """Render scalar-ish JSON values as readable text."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def anchor(text: str) -> str:
    """GitHub-like simple anchor helper for internal links."""
    out = []
    for ch in text.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in (" ", "-", "_", "/"):
            out.append("-")
    result = "".join(out)
    while "--" in result:
        result = result.replace("--", "-")
    return result.strip("-")


def heading(level: int, title: str) -> str:
    return f"{'#' * level} {title}\n\n"


def bullet_list(values: list[Any]) -> str:
    if not values:
        return ""
    lines = []
    for value in values:
        if isinstance(value, dict):
            lines.append(f"- {inline_dict(value)}")
        elif isinstance(value, list):
            lines.append(f"- {', '.join(scalar_to_text(v) for v in value)}")
        else:
            lines.append(f"- {scalar_to_text(value)}")
    return "\n".join(lines) + "\n\n"


def inline_dict(value: dict[str, Any]) -> str:
    parts = []
    for key, item in value.items():
        if isinstance(item, (dict, list)):
            parts.append(f"`{key}`: {json.dumps(item, ensure_ascii=False, sort_keys=True)}")
        else:
            parts.append(f"`{key}`: {scalar_to_text(item)}")
    return "; ".join(parts)


def fenced_code(text: str, language: str = "") -> str:
    fence = "```"
    return f"{fence}{language}\n{text.rstrip()}\n{fence}\n\n"


def render_metadata(data: dict[str, Any]) -> str:
    lines = [heading(2, "Inventory Metadata")]

    rows: list[tuple[str, Any]] = []
    for key in ("schema_version", "project", "generated_from"):
        if key in data:
            rows.append((key, data[key]))

    if not rows:
        return ""

    lines.append("| Field | Value |\n")
    lines.append("| --- | --- |\n")
    for key, value in rows:
        lines.append(f"| `{md_escape_cell(key)}` | {md_escape_cell(value)} |\n")
    lines.append("\n")
    return "".join(lines)


def render_binding_readiness(data: dict[str, Any]) -> str:
    readiness = data.get("binding_readiness")
    if not isinstance(readiness, dict):
        return ""

    lines = [heading(2, "Binding Readiness")]

    notes = readiness.get("notes")
    rows = [(k, v) for k, v in readiness.items() if k != "notes"]

    if rows:
        lines.append("| Target | Status |\n")
        lines.append("| --- | --- |\n")
        for key, value in rows:
            lines.append(f"| `{md_escape_cell(key)}` | {md_escape_cell(value)} |\n")
        lines.append("\n")

    if notes:
        lines.append("Notes:\n\n")
        if isinstance(notes, list):
            lines.append(bullet_list(notes))
        else:
            lines.append(f"{scalar_to_text(notes)}\n\n")

    return "".join(lines)


def render_workspace_summary(crates: list[dict[str, Any]]) -> str:
    lines = [heading(2, "Workspace Summary")]

    lines.append("| Crate | Path | Purpose | Status |\n")
    lines.append("| --- | --- | --- | --- |\n")

    for crate in crates:
        name = crate.get("name", "")
        path = crate.get("path", "")
        purpose = crate.get("purpose", "")
        status = crate.get("status", "")
        lines.append(
            f"| `{md_escape_cell(name)}` | `{md_escape_cell(path)}` | "
            f"{md_escape_cell(purpose)} | {md_escape_cell(status)} |\n"
        )

    lines.append("\n")
    return "".join(lines)


def render_item(item: dict[str, Any]) -> str:
    lines: list[str] = []

    name = scalar_to_text(item.get("name", "unnamed"))
    kind = scalar_to_text(item.get("kind", "item"))
    implemented = item.get("implemented")

    title = f"`{name}`"
    details = [kind]
    if implemented is not None:
        details.append("implemented" if implemented else "not implemented")
    if item.get("since_milestone"):
        details.append(f"since {item['since_milestone']}")

    lines.append(f"- {title} - {', '.join(details)}\n")

    signature = item.get("signature")
    if signature:
        lines.append(f"  - Signature: `{signature}`\n")

    description = item.get("description")
    if description:
        lines.append(f"  - {md_escape_text(description)}\n")

    for key, value in item.items():
        if key in {
            "name",
            "kind",
            "signature",
            "description",
            "since_milestone",
            "implemented",
        }:
            continue

        if isinstance(value, list):
            if value:
                lines.append(f"  - `{key}`:\n")
                for entry in value:
                    lines.append(f"    - {scalar_to_text(entry)}\n")
        elif isinstance(value, dict):
            if value:
                lines.append(f"  - `{key}`: {inline_dict(value)}\n")
        elif value not in (None, ""):
            lines.append(f"  - `{key}`: {scalar_to_text(value)}\n")

    return "".join(lines)


def render_module(module: dict[str, Any]) -> str:
    lines: list[str] = []

    name = scalar_to_text(module.get("name", "unnamed"))
    path = module.get("path")

    if path:
        lines.append(heading(4, f"`{name}` module"))
        lines.append(f"Path: `{path}`\n\n")
    else:
        lines.append(heading(4, f"`{name}` module"))

    description = module.get("description")
    if description:
        lines.append(f"{description}\n\n")

    items = module.get("items")
    if isinstance(items, list) and items:
        lines.append("Public items:\n\n")
        for item in items:
            if isinstance(item, dict):
                lines.append(render_item(item))
            else:
                lines.append(f"- {scalar_to_text(item)}\n")
        lines.append("\n")

    for key, value in module.items():
        if key in {"name", "path", "description", "items"}:
            continue
        lines.append(render_unknown_section(key, value, level=5))

    return "".join(lines)


def render_crate(crate: dict[str, Any]) -> str:
    lines: list[str] = []

    name = scalar_to_text(crate.get("name", "unnamed"))
    lines.append(heading(3, f"`{name}`"))

    path = crate.get("path")
    if path:
        lines.append(f"Path: `{path}`\n\n")

    purpose = crate.get("purpose")
    if purpose:
        lines.append(f"{purpose}\n\n")

    status = crate.get("status")
    milestones = crate.get("milestones")

    summary_rows: list[tuple[str, Any]] = []
    if status:
        summary_rows.append(("status", status))
    if milestones:
        summary_rows.append(("milestones", ", ".join(scalar_to_text(m) for m in milestones)))

    if summary_rows:
        lines.append("| Field | Value |\n")
        lines.append("| --- | --- |\n")
        for key, value in summary_rows:
            lines.append(f"| `{md_escape_cell(key)}` | {md_escape_cell(value)} |\n")
        lines.append("\n")

    features = crate.get("features")
    if isinstance(features, list) and features:
        lines.append(heading(4, "Features"))
        lines.append(bullet_list(features))

    modules = crate.get("modules")
    if isinstance(modules, list) and modules:
        lines.append(heading(4, "Public Modules"))
        for module in modules:
            if isinstance(module, dict):
                lines.append(render_module(module))
            else:
                lines.append(f"- {scalar_to_text(module)}\n")
        lines.append("\n")

    for key, value in crate.items():
        if key in {"name", "path", "purpose", "status", "milestones", "features", "modules"}:
            continue
        lines.append(render_unknown_section(key, value, level=4))

    return "".join(lines)


def render_crates(data: dict[str, Any]) -> str:
    crates = data.get("crates")
    if not isinstance(crates, list):
        return ""

    crate_dicts = [crate for crate in crates if isinstance(crate, dict)]
    lines = [render_workspace_summary(crate_dicts), heading(2, "Crates")]

    for crate in crate_dicts:
        lines.append(render_crate(crate))

    return "".join(lines)


def render_cli(data: dict[str, Any]) -> str:
    cli = data.get("cli")
    if not isinstance(cli, dict):
        return ""

    lines = [heading(2, "CLI")]

    binary = cli.get("binary")
    if binary:
        lines.append(f"Binary: `{binary}`\n\n")

    commands = cli.get("commands")
    if isinstance(commands, list) and commands:
        lines.append("| Command | Summary | Status |\n")
        lines.append("| --- | --- | --- |\n")
        for command in commands:
            if isinstance(command, dict):
                name = command.get("name", "")
                summary = command.get("summary", command.get("description", ""))
                status = command.get("status", "")
                lines.append(
                    f"| `{md_escape_cell(name)}` | {md_escape_cell(summary)} | {md_escape_cell(status)} |\n"
                )
            else:
                lines.append(f"| `{md_escape_cell(command)}` |  |  |\n")
        lines.append("\n")

        for command in commands:
            if not isinstance(command, dict):
                continue

            name = scalar_to_text(command.get("name", "unnamed"))
            lines.append(heading(3, f"`{name}`"))

            for field in ("summary", "description", "status"):
                value = command.get(field)
                if value:
                    lines.append(f"**{field.replace('_', ' ').title()}:** {scalar_to_text(value)}\n\n")

            for key, value in command.items():
                if key in {"name", "summary", "description", "status"}:
                    continue
                lines.append(render_unknown_section(key, value, level=4))

    for key, value in cli.items():
        if key in {"binary", "commands"}:
            continue
        lines.append(render_unknown_section(key, value, level=3))

    return "".join(lines)


def render_cdc_inventory(data: dict[str, Any]) -> str:
    cdc = data.get("cdc_inventory")
    if not isinstance(cdc, dict):
        return ""

    lines = [heading(2, "CDC Inventory")]

    scope = cdc.get("scope")
    if scope:
        lines.append(f"Scope: `{scope}`\n\n")

    for key, value in cdc.items():
        if key == "scope":
            continue
        lines.append(render_unknown_section(key, value, level=3))

    return "".join(lines)


def render_security_notes(data: dict[str, Any]) -> str:
    notes = data.get("security_notes")
    if not isinstance(notes, dict):
        return ""

    lines = [heading(2, "Security-Relevant API Notes")]
    lines.append(
        "This section is generated from security-related notes in the machine-readable API inventory. "
        "For the authoritative public security posture, see `docs/SECURITY.md`.\n\n"
    )

    for key, value in notes.items():
        lines.append(render_unknown_section(key, value, level=3))

    return "".join(lines)


def render_unknown_section(key: str, value: Any, level: int) -> str:
    """Render arbitrary JSON content in a stable, readable way."""
    title = key.replace("_", " ").title()
    lines = [heading(level, title)]

    if isinstance(value, dict):
        if not value:
            return ""
        scalar_rows: list[tuple[str, Any]] = []
        complex_items: list[tuple[str, Any]] = []

        for child_key, child_value in value.items():
            if isinstance(child_value, (dict, list)):
                complex_items.append((child_key, child_value))
            else:
                scalar_rows.append((child_key, child_value))

        if scalar_rows:
            lines.append("| Field | Value |\n")
            lines.append("| --- | --- |\n")
            for child_key, child_value in scalar_rows:
                lines.append(
                    f"| `{md_escape_cell(child_key)}` | {md_escape_cell(child_value)} |\n"
                )
            lines.append("\n")

        for child_key, child_value in complex_items:
            lines.append(render_unknown_section(child_key, child_value, level=level + 1))

    elif isinstance(value, list):
        if not value:
            return ""

        if all(isinstance(item, dict) for item in value):
            for idx, item in enumerate(value, start=1):
                assert isinstance(item, dict)
                name = item.get("name") or item.get("id") or item.get("command") or item.get("type")
                section_title = scalar_to_text(name) if name else f"Entry {idx}"
                lines.append(heading(level + 1, section_title))

                scalar_rows = []
                complex_items = []
                for child_key, child_value in item.items():
                    if isinstance(child_value, (dict, list)):
                        complex_items.append((child_key, child_value))
                    else:
                        scalar_rows.append((child_key, child_value))

                if scalar_rows:
                    lines.append("| Field | Value |\n")
                    lines.append("| --- | --- |\n")
                    for child_key, child_value in scalar_rows:
                        lines.append(
                            f"| `{md_escape_cell(child_key)}` | {md_escape_cell(child_value)} |\n"
                        )
                    lines.append("\n")

                for child_key, child_value in complex_items:
                    lines.append(render_unknown_section(child_key, child_value, level=level + 2))
        else:
            lines.append(bullet_list(value))

    else:
        text = scalar_to_text(value)
        if text:
            lines.append(f"{text}\n\n")
        else:
            return ""

    return "".join(lines)


def render_api_markdown(data: dict[str, Any]) -> str:
    parts = [
        SPDX_AND_GENERATED_HEADER,
        VISIBLE_INTRO,
        "\n",
        render_metadata(data),
        render_binding_readiness(data),
        render_crates(data),
        render_cli(data),
        render_cdc_inventory(data),
        render_security_notes(data),
    ]

    markdown = "".join(part for part in parts if part)

    # Normalize trailing whitespace and ensure exactly one final newline.
    lines = [line.rstrip() for line in markdown.splitlines()]
    return "\n".join(lines).rstrip() + "\n"


def load_json(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
    except FileNotFoundError:
        raise SystemExit(f"error: input file not found: {path}") from None
    except json.JSONDecodeError as exc:
        raise SystemExit(f"error: invalid JSON in {path}: {exc}") from None

    if not isinstance(data, dict):
        raise SystemExit(f"error: top-level JSON value must be an object: {path}")

    return data


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"input JSON file, default: {DEFAULT_INPUT.relative_to(REPO_ROOT)}",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"output Markdown file, default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)}",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if output file is missing or stale",
    )

    args = parser.parse_args(argv)

    data = load_json(args.input)
    generated = render_api_markdown(data)

    if args.check:
        try:
            existing = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"error: generated file is missing: {args.output}", file=sys.stderr)
            return 1

        if existing != generated:
            print(
                f"error: {args.output} is stale; run `python tools/generate_api_md.py`",
                file=sys.stderr,
            )
            return 1

        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8", newline="\n")
    print(f"generated {args.output.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
