#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 M. Kasim Doenmez
# SPDX-License-Identifier: Apache-2.0

"""
Generate docs/M13_AUDIT_FINDINGS.md from docs/machine-readable/M13_AUDIT_FINDINGS.json.

The JSON registry is authoritative. This generator intentionally renders a
concise human-readable view focused on audit coverage and findings. Detailed
operational metadata and machine-processing fields remain in the JSON.

Usage from repository root:

    python tools/generate_audit_md.py

Check mode:

    python tools/generate_audit_md.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Iterable

from mdgen import (
    REPO_ROOT,
    heading,
    load_json,
    md_code,
    md_escape_cell,
    md_escape_text,
    normalize_markdown,
    validate_json_document,
    write_or_check,
)


DEFAULT_INPUT = REPO_ROOT / "docs/machine-readable" / "M13_AUDIT_FINDINGS.json"
DEFAULT_SCHEMA = REPO_ROOT / "docs/machine-readable" / "M13_AUDIT_FINDINGS.schema.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "M13_AUDIT_FINDINGS.md"
EXPECTED_SCHEMA_ID = "urn:sar:m13-audit-findings:schema:2"

HEADER = """<!--
SPDX-FileCopyrightText: 2026 M. Kasim Doenmez
SPDX-License-Identifier: Apache-2.0
-->

<!--
This file is generated from docs/machine-readable/M13_AUDIT_FINDINGS.json.
Do not edit this file by hand.

Regenerate with:

    python tools/generate_audit_md.py

Check without modifying files:

    python tools/generate_audit_md.py --check
-->
"""

INTRO = """# M13 Audit Findings

This file is generated from `docs/machine-readable/M13_AUDIT_FINDINGS.json`.

Do not edit this file by hand. Update the authoritative JSON registry and regenerate this Markdown file instead.

This is a concise human-readable view focused on audit coverage and findings. Full scope metadata, evidence metadata, notes, and machine-processing fields remain available in the JSON registry.

Open remediation findings do not imply that an audit scope is incomplete. Audit completion records that the defined review work was performed and classified; remediation is tracked separately by the assigned milestone.
"""


def dict_items(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def string_items(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item) for item in value]


def render_key_value_table(rows: Iterable[tuple[str, Any]]) -> str:
    materialized = [(label, value) for label, value in rows if value not in (None, "")]
    if not materialized:
        return ""

    lines = ["| Field | Value |\n", "| --- | --- |\n"]
    for label, value in materialized:
        lines.append(f"| {md_escape_cell(label)} | {md_escape_cell(value)} |\n")
    lines.append("\n")
    return "".join(lines)


def render_bullet_list(title: str, values: list[str], *, level: int = 4) -> str:
    if not values:
        return ""
    lines = [heading(level, title)]
    for value in values:
        lines.append(f"* {md_escape_text(value)}\n")
    lines.append("\n")
    return "".join(lines)


def render_text_field(title: str, value: Any, *, level: int = 4) -> str:
    if value in (None, ""):
        return ""
    return heading(level, title) + f"{md_escape_text(value)}\n\n"


def render_audit_summary(data: dict[str, Any]) -> str:
    scopes = dict_items(data.get("audit_scopes"))
    lines = [heading(2, "Audit Summary")]
    lines.append(f"Registry status: {md_code(data.get('registry_status', ''))}\n\n")

    lines.append("| Scope | Status | Title |\n")
    lines.append("| --- | --- | --- |\n")
    for scope in scopes:
        lines.append(
            f"| {md_code(scope.get('milestone', ''))} | "
            f"{md_code(scope.get('status', ''))} | "
            f"{md_escape_cell(scope.get('title', ''))} |\n"
        )
    lines.append("\n")

    for scope in scopes:
        objectives = dict_items(scope.get("objectives"))
        if not objectives:
            continue
        lines.append(heading(3, f"{scope.get('milestone', '')} Audit Coverage"))
        lines.append("| Objective | Status | Outcome | Title |\n")
        lines.append("| --- | --- | --- | --- |\n")
        for objective in objectives:
            lines.append(
                f"| {md_code(objective.get('id', ''))} | "
                f"{md_code(objective.get('status', ''))} | "
                f"{md_code(objective.get('outcome', ''))} | "
                f"{md_escape_cell(objective.get('title', ''))} |\n"
            )
        lines.append("\n")

    return "".join(lines)


def render_findings_index(findings: list[dict[str, Any]]) -> str:
    lines = [heading(2, "Findings Index")]
    lines.append("| ID | Type | Status | Severity | Priority | Owner | Title |\n")
    lines.append("| --- | --- | --- | --- | --- | --- | --- |\n")
    for finding in findings:
        lines.append(
            f"| {md_code(finding.get('id', ''))} | "
            f"{md_code(finding.get('finding_type', ''))} | "
            f"{md_code(finding.get('status', ''))} | "
            f"{md_code(finding.get('severity', ''))} | "
            f"{md_code(finding.get('priority', ''))} | "
            f"{md_code(finding.get('resolution_owner', ''))} | "
            f"{md_escape_cell(finding.get('title', ''))} |\n"
        )
    lines.append("\n")
    return "".join(lines)


def render_evidence(evidence: list[dict[str, Any]]) -> str:
    if not evidence:
        return ""

    lines = [heading(4, "Evidence")]
    for item in evidence:
        artifact = md_code(item.get("artifact", ""))
        locator = item.get("locator")
        location = f" ({md_escape_text(locator)})" if locator else ""
        description = md_escape_text(item.get("description", ""))
        lines.append(f"* {artifact}{location}: {description}\n")

        reproduction = item.get("reproduction")
        if reproduction:
            lines.append(f"  * Reproduction: {md_escape_text(reproduction)}\n")
    lines.append("\n")
    return "".join(lines)


def render_normative_basis(items: list[dict[str, Any]]) -> str:
    if not items:
        return ""

    lines = [heading(4, "Normative Basis")]
    for item in items:
        document = md_code(item.get("document", ""))
        locator = item.get("locator")
        location = f" ({md_escape_text(locator)})" if locator else ""
        requirement = md_escape_text(item.get("requirement", ""))
        lines.append(f"* {document}{location}: {requirement}\n")
    lines.append("\n")
    return "".join(lines)


def render_remediation(remediation: Any) -> str:
    if not isinstance(remediation, dict):
        return ""

    requirements = string_items(remediation.get("requirements"))
    constraints = string_items(remediation.get("constraints"))
    if not requirements and not constraints:
        return ""

    lines = [heading(4, "Remediation")]
    for requirement in requirements:
        lines.append(f"* {md_escape_text(requirement)}\n")
    for constraint in constraints:
        lines.append(f"* Constraint: {md_escape_text(constraint)}\n")
    lines.append("\n")
    return "".join(lines)


def render_verification(verification: Any) -> str:
    if not isinstance(verification, dict):
        return ""

    requirement = verification.get("test_requirement")
    criteria = string_items(verification.get("acceptance_criteria"))
    evidence_artifacts = string_items(verification.get("evidence_artifacts"))

    if requirement == "not_required" and not criteria and not evidence_artifacts:
        return ""

    lines = [heading(4, "Verification")]
    if requirement:
        lines.append(f"Requirement: {md_code(requirement)}\n\n")
    for criterion in criteria:
        lines.append(f"* {md_escape_text(criterion)}\n")
    for artifact in evidence_artifacts:
        lines.append(f"* Evidence artifact: {md_code(artifact)}\n")
    if criteria or evidence_artifacts:
        lines.append("\n")
    return "".join(lines)


def render_relationships(relationships: Any) -> str:
    if not isinstance(relationships, dict) or not relationships:
        return ""

    labels = {
        "depends_on": "Depends on",
        "blocked_by": "Blocked by",
        "related_findings": "Related findings",
        "duplicates": "Duplicates",
        "supersedes": "Supersedes",
        "superseded_by": "Superseded by",
    }
    lines = [heading(4, "Relationships")]
    rendered = False
    for key, label in labels.items():
        values = string_items(relationships.get(key))
        if not values:
            continue
        rendered = True
        lines.append(f"* **{label}:** {', '.join(md_code(value) for value in values)}\n")

    if not rendered:
        return ""
    lines.append("\n")
    return "".join(lines)


def render_resolution(resolution: Any) -> str:
    if not isinstance(resolution, dict):
        return ""

    lines = [heading(4, "Resolution")]
    decision = resolution.get("decision_type")
    date = resolution.get("resolved_date")
    if decision or date:
        details: list[str] = []
        if decision:
            details.append(md_code(decision))
        if date:
            details.append(md_code(date))
        lines.append(" - ".join(details) + "\n\n")

    summary = resolution.get("summary")
    if summary:
        lines.append(f"{md_escape_text(summary)}\n\n")

    rationale = resolution.get("rationale")
    if rationale:
        lines.append(f"Rationale: {md_escape_text(rationale)}\n\n")
    return "".join(lines)


def render_finding(finding: dict[str, Any]) -> str:
    finding_id = finding.get("id", "")
    title = finding.get("title", "")
    compatibility = finding.get("compatibility_impact")

    rows: list[tuple[str, Any]] = [
        ("Type", finding.get("finding_type")),
        ("Source milestone", finding.get("source_milestone")),
        ("Status", finding.get("status")),
        ("Severity", finding.get("severity")),
        ("Priority", finding.get("priority")),
        ("Owner", finding.get("resolution_owner")),
    ]
    if compatibility not in (None, "", "none"):
        rows.append(("Compatibility", compatibility))

    lines = [heading(3, f"{finding_id}: {title}")]
    lines.append(render_key_value_table(rows))
    lines.append(render_text_field("Summary", finding.get("summary")))
    lines.append(render_text_field("Current Behavior", finding.get("current_behavior")))
    lines.append(render_text_field("Expected Behavior", finding.get("expected_behavior")))
    lines.append(render_text_field("Normative Question", finding.get("normative_question")))
    lines.append(render_text_field("Impact", finding.get("impact")))
    lines.append(render_evidence(dict_items(finding.get("evidence"))))
    lines.append(render_normative_basis(dict_items(finding.get("normative_basis"))))
    lines.append(render_remediation(finding.get("remediation")))
    lines.append(render_verification(finding.get("verification")))
    lines.append(render_relationships(finding.get("relationships")))
    lines.append(render_resolution(finding.get("resolution")))
    return "".join(lines)


def render_findings(data: dict[str, Any]) -> str:
    findings = dict_items(data.get("findings"))
    lines = [render_findings_index(findings), heading(2, "Finding Details")]
    for finding in findings:
        lines.append(render_finding(finding))
    return "".join(lines)


def render_audit_markdown(data: dict[str, Any]) -> str:
    parts = [
        HEADER,
        INTRO,
        "\n",
        render_audit_summary(data),
        render_findings(data),
    ]
    return normalize_markdown("".join(parts))


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--schema", type=Path, default=DEFAULT_SCHEMA)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if output file is missing or stale",
    )
    args = parser.parse_args(argv)

    data = load_json(args.input)
    validate_json_document(
        data,
        schema_path=args.schema,
        expected_schema_id=EXPECTED_SCHEMA_ID,
    )
    generated = render_audit_markdown(data)
    return write_or_check(
        output_path=args.output,
        generated=generated,
        check=args.check,
        regenerate_command="python tools/generate_audit_md.py",
    )


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
